### ISSUE TITLE
support AEAD methods

### ISSUE THREAD

**Issue by facudy** [so898/Potatso#1]
to support AEAD methods (aes-128-gcm, aes-192-gcm, aes-256-gcm, chacha20-poly1305, chacha20-ietf-poly1305)

do you have a plan to work on it?

Thank you .

**Comment by so898** [comment]
I already done these supports.
There are many things on the check list before release.
When there is a release, I will let you know.

**Comment by weqeo** [comment]
Hello,did u support AEAD methods now? i hope i can learn how to do it from u~
thank u
